#!/usr/bin/env node
/**
 * One-command bootstrap for a fresh clone.
 *
 *   npm install && npm run setup
 *
 * What it does
 *   1. Creates `config/<TEST_ENV>.env` from `.env.example`, filling in the
 *      non-secret defaults for that environment (see NON_SECRET_DEFAULTS).
 *      Never overwrites an existing file — a developer's edited values win.
 *   2. Installs the Playwright browser binaries (`npx playwright install`).
 *
 * Why a script instead of README steps: every file under `config/` is
 * gitignored (`config/*.env`, `config/*.local.env`), so a fresh clone has no
 * environment file at all — and `.env.example` ships `STORE_BASE_URL` blank on
 * purpose. Doing this by hand and getting it wrong makes `requireEnv()`
 * (utils/env.ts) throw on the very first test run. See bug-292.
 *
 * Flags
 *   --chromium-only   install only the browser CI uses (faster, ~1 browser)
 *   --with-deps       also install OS-level browser dependencies (Linux/CI)
 *   --skip-browsers   only create the env file
 *
 * Environment
 *   TEST_ENV   which config pair to create (default: development)
 *
 * Exit code 0 on success, 1 on any failure.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

/** Repository root — this file lives in <root>/scripts/. */
const ROOT = path.resolve(__dirname, '..');
const EXAMPLE_FILE = path.join(ROOT, '.env.example');
const CONFIG_DIR = path.join(ROOT, 'config');

/**
 * Non-secret, safe-to-commit defaults injected into a newly created env file.
 * Keep secrets OUT of here: they belong in `config/<env>.local.env` or CI
 * secrets. An environment absent from this map gets the blank template, and
 * the script tells the user which variables they still have to fill in.
 */
const NON_SECRET_DEFAULTS = {
  // Public, credential-free demo storefront targeted by tests/e2e/wishlist/**.
  development: { STORE_BASE_URL: 'https://storedemo.testdino.com' },
};

const ICON = { ok: '[OK]', skip: '[SKIP]', run: '[RUN]', warn: '[WARN]', fail: '[FAIL]' };

let stepNo = 0;
const step = (title) => console.log(`\n(${++stepNo}) ${title}`);
const ok = (msg) => console.log(`  ${ICON.ok}   ${msg}`);
const skip = (msg) => console.log(`  ${ICON.skip} ${msg}`);
const run = (msg) => console.log(`  ${ICON.run}  ${msg}`);
const warn = (msg) => console.warn(`  ${ICON.warn} ${msg}`);
const fail = (msg) => console.error(`  ${ICON.fail} ${msg}`);

/** Relative, forward-slashed path for stable log output across platforms. */
const rel = (abs) => path.relative(ROOT, abs).split(path.sep).join('/');

/**
 * Rewrites `KEY=` assignments in a dotenv template, preserving all comments,
 * blank lines and key order. Only keys present in `values` are touched.
 *
 * @param {string} template raw contents of .env.example
 * @param {Record<string, string>} values key -> value to apply
 * @returns {{ content: string, applied: string[] }}
 */
function applyDefaults(template, values) {
  const applied = [];
  const content = template
    .split(/\r?\n/)
    .map((line) => {
      const match = /^(\s*)([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/.exec(line);
      if (match === null) return line; // comment or blank line — keep verbatim
      const [, indent, key] = match;
      if (!Object.prototype.hasOwnProperty.call(values, key)) return line;
      applied.push(key);
      return `${indent}${key}=${values[key]}`;
    })
    .join('\n');
  return { content, applied };
}

/**
 * Replaces the template's leading comment block with a banner appropriate for a
 * generated file. `.env.example` opens with "COMMIT THIS FILE ONLY", which is
 * true of the template but dangerously wrong once copied into `config/`, where
 * every file is gitignored and may later hold real values.
 */
function replaceHeader(content, env) {
  const banner = [
    '# ---------------------------------------------------------------------------',
    '# GENERATED by `npm run setup` from .env.example — safe to edit.',
    '# Gitignored (config/*.env): do NOT commit it.',
    `# Non-secret defaults only. Secrets belong in config/${env}.local.env or CI secrets.`,
    '# ---------------------------------------------------------------------------',
  ].join('\n');

  const lines = content.split(/\r?\n/);
  let i = 0;
  while (i < lines.length && lines[i].startsWith('#')) i += 1; // first comment block only
  return `${banner}\n${lines.slice(i).join('\n')}`;
}

/** Returns the names of variables that are declared but still blank. */
function blankVars(content) {
  return content.split(/\r?\n/).reduce((acc, line) => {
    const match = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*$/.exec(line);
    if (match !== null) acc.push(match[1]);
    return acc;
  }, []);
}

/**
 * Creates `config/<env>.env` unless it already exists.
 * @returns {{ created: boolean, target: string }}
 */
function createEnvFile(env) {
  const target = path.join(CONFIG_DIR, `${env}.env`);

  if (fs.existsSync(target)) {
    skip(`${rel(target)} already exists — left untouched (your values are preserved).`);
    const existingBlanks = blankVars(fs.readFileSync(target, 'utf8'));
    if (existingBlanks.length > 0) {
      warn(
        `${rel(target)} has blank variable(s): ${existingBlanks.join(', ')}. ` +
          `Tests using them will fail via requireEnv() until you fill them in.`,
      );
    }
    return { created: false, target };
  }

  if (!fs.existsSync(EXAMPLE_FILE)) {
    throw new Error(
      `Template ${rel(EXAMPLE_FILE)} not found. It is committed to the repo — ` +
        `re-clone or restore it, then run "npm run setup" again.`,
    );
  }

  // A fresh clone has no config/ directory at all: git cannot track an empty
  // folder and every file inside it is gitignored.
  fs.mkdirSync(CONFIG_DIR, { recursive: true });

  const defaults = { TEST_ENV: env, ...(NON_SECRET_DEFAULTS[env] ?? {}) };
  const template = replaceHeader(fs.readFileSync(EXAMPLE_FILE, 'utf8'), env);
  const { content, applied } = applyDefaults(template, defaults);

  fs.writeFileSync(target, content, 'utf8');
  ok(`Created ${rel(target)} from ${rel(EXAMPLE_FILE)}.`);
  if (applied.length > 0) ok(`Applied non-secret default(s): ${applied.join(', ')}.`);

  const remaining = blankVars(content);
  if (remaining.length > 0) {
    warn(
      `Still blank (no safe default for "${env}"): ${remaining.join(', ')}. ` +
        `Edit ${rel(target)} before running the tests.`,
    );
  }
  return { created: true, target };
}

/** Installs Playwright browsers. Throws when the install command fails. */
function installBrowsers({ chromiumOnly, withDeps }) {
  const args = ['install'];
  if (withDeps) args.push('--with-deps');
  if (chromiumOnly) args.push('chromium');

  run(`npx playwright ${args.join(' ')}`);

  // Invoke the locally installed Playwright CLI through `node` directly rather
  // than `npx`: no shell (Windows cannot spawn a .cmd shim without `shell:true`,
  // which Node >=22 deprecates as DEP0190 for argument concatenation), and it
  // guarantees the version pinned in package-lock.json is the one that runs.
  let cli;
  try {
    // Subpath must be './cli' — the package's "exports" map does not expose './cli.js'.
    cli = require.resolve('@playwright/test/cli', { paths: [ROOT] });
  } catch {
    throw new Error(
      'Could not resolve @playwright/test. Run "npm install" (or "npm ci") before "npm run setup".',
    );
  }

  const result = spawnSync(process.execPath, [cli, ...args], { cwd: ROOT, stdio: 'inherit' });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(
      `"npx playwright ${args.join(' ')}" exited with code ${result.status}. ` +
        `Re-run it manually to see the full output (on Linux add --with-deps).`,
    );
  }
  ok(chromiumOnly ? 'Chromium installed.' : 'Browser binaries installed.');
  if (chromiumOnly) {
    warn(
      'Chromium only: "npm test" also runs the firefox/webkit projects and will ' +
        'fail with "Executable doesn\'t exist". Use "npm run test:chromium", or ' +
        're-run "npm run setup" without --chromium-only.',
    );
  }
}

function main() {
  const argv = process.argv.slice(2);
  const has = (flag) => argv.includes(flag);
  const env = (process.env.TEST_ENV ?? 'development').trim() || 'development';

  console.log('automation-testing — setup');
  console.log(`  root:     ${ROOT}`);
  console.log(`  TEST_ENV: ${env}`);

  step(`Environment file (config/${env}.env)`);
  const { created, target } = createEnvFile(env);

  step('Playwright browsers');
  if (has('--skip-browsers')) {
    skip('--skip-browsers passed — browser install not attempted.');
  } else {
    installBrowsers({ chromiumOnly: has('--chromium-only'), withDeps: has('--with-deps') });
  }

  console.log('\nSetup complete.');
  console.log(`  env file: ${rel(target)} (${created ? 'created' : 'already existed'})`);
  console.log('  next:     npm run test:smoke');
}

try {
  main();
} catch (error) {
  fail(error instanceof Error ? error.message : String(error));
  console.error('\nSetup failed. See README §3 for the manual steps.');
  process.exit(1);
}
